# Generated by Django 5.0.6 on 2024-06-08 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_grocerylist_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="purchased",
        ),
    ]
